[project]
name = "ttadapters"
version = "1.0.0"
description = "Pluggable Test-time Adapter Implementations"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "torchaudio",
    "torchvision",
    "transformers>=4.52.3",
    "shift-dev",
]

[tool.uv.sources]
shift-dev = { git = "https://github.com/robustaim/shift-dev" }
