method : 
  actmad : 
    make_scheduler : false
    cean_bn_extract : null
  norm :
    make_scheduler : false
    momentum : 0.05
  dua :
    make_scheduler : false
    norm_pre : 0.07
    decay_factor : 0.97
    min_momentum_constant : 0.01
  mean_teacher :
        make_scheduler : true

device : "cuda:0"
save_dir : "./direct_method_checkpoints"
model_arch : "rt_detr"
reference_model_id : "PekingU/rtdetr_r50vd"
model_states : "/workspace/ptta/RT-DETR_R50vd_SHIFT_CLEAR.safetensors"

data_root : "/workspace/ptta/data"
image_size : 800
class_num : 6
valid_batch : 1

optimizer : "SGD" # or "AdamW"
lr : 1e-4

